var nameList = [
    'Aarav', 'Vivaan', 'Aditya', 'Arjun', 'Sai', 'Rishi', 'Krishna', 
    'Lakshay', 'Ishaan', 'Rohan', 'Karan', 'Dhruv', 'Ananya', 'Aditi', 
    'Ishita', 'Pooja', 'Simran', 'Sneha', 'Riya', 'Maya', 'Avni', 'Diya', 
    'Raj', 'Vikram', 'Ajay', 'Dev', 'Meera', 'Sanjay', 'Manish', 'Priya', 
    'Nisha', 'Akash', 'Rahul', 'Vikas', 'Ashok', 'Anil', 'Neha', 'Kriti', 
    'Shreya', 'Harsh', 'Gautam', 'Armaan', 'Kabir', 'Siddharth', 'Tanmay', 
    'Amrita', 'Komal', 'Tara', 'Jai', 'Suresh', 'Lakshmi', 'Parvati', 
    'Amit', 'Ramesh', 'Varun', 'Sakshi', 'Kiran', 'Akhil', 'Nitin', 
    'Deepak', 'Vijay', 'Aryan', 'Chaitanya', 'Ankita', 'Leela', 'Bhavna', 
    'Pankaj', 'Rekha', 'Sanjana', 'Shivani', 'Manoj', 'Kartik', 'Om', 
    'Naveen', 'Arvind', 'Ruchi', 'Tanu', 'Harsha', 'Hemant', 'Rajesh', 
    'Amrita', 'Yash', 'Ravindra', 'Jitendra', 'Anurag', 'Sonia', 'Gopal', 
    'Sunil', 'Siddhi', 'Uma', 'Mohan', 'Hina', 'Geeta', 'Tarun', 'Mukesh', 
    'Lalit', 'Vinod', 'Bharat', 'Rajiv', 'Ashwin', 'Santosh'
];

var messageList = [
    "Hello, how are you?",
    "What's up?",
    "Good morning!",
    "Good night!",
    "Have a great day!",
    "See you soon!",
    "Take care!",
    "I'm on my way.",
    "Let's meet tomorrow.",
    "What time is the meeting?",
    "Can you help me?",
    "Call me when you're free.",
    "I'll get back to you.",
    "Thank you!",
    "You're welcome.",
    "Sorry for the delay.",
    "No worries.",
    "Where are you?",
    "I'm running late.",
    "Let's grab lunch.",
    "Congrats on your success!",
    "That's amazing!",
    "How's everything going?",
    "Catch you later.",
    "I'm at work.",
    "Just chilling.",
    "What's your plan for today?",
    "It's been a long day.",
    "Let's celebrate!",
    "All the best!",
    "Don't forget to bring it.",
    "Can I borrow it?",
    "I'll send it to you.",
    "What do you think?",
    "Sounds like a plan.",
    "Let's do it!",
    "I'm not sure about that.",
    "Absolutely!",
    "I'm here if you need me.",
    "Let's go out tonight.",
    "I'm feeling great!",
    "Happy birthday!",
    "Congratulations!",
    "Can you explain that?",
    "It was nice meeting you.",
    "What's for dinner?",
    "How was your weekend?",
    "I'll be there in 10 minutes.",
    "Let's get started.",
    "Keep it up!",
    "I'm so proud of you.",
    "Take a break.",
    "Let's go for a walk.",
    "I'm feeling a bit tired.",
    "What's the update?",
    "Don't forget to smile.",
    "Let me check.",
    "That sounds interesting.",
    "Let's catch up soon.",
    "I'm free after 6 PM.",
    "Can we reschedule?",
    "I'll let you know.",
    "Please wait a moment.",
    "That's a great idea!",
    "What's new with you?",
    "I completely agree.",
    "You're doing great!",
    "Let me know if you need anything.",
    "Thanks for understanding.",
    "I appreciate it.",
    "Talk to you later.",
    "Good luck!",
    "Let's discuss it later.",
    "I don't think so.",
    "It's okay, no problem.",
    "What a beautiful day!",
    "I'll join you shortly.",
    "Can you share the details?",
    "It's really nice.",
    "Take it easy.",
    "I hope everything's fine.",
    "Let's take it step by step.",
    "Keep me posted.",
    "Drive safe.",
    "What's the agenda?",
    "I'll do my best.",
    "It's time to celebrate!",
    "Don't forget to relax.",
    "It's a pleasure to help.",
    "I'll manage it.",
    "Looking forward to it!",
    "That was unexpected.",
    "Let's not rush.",
    "See you at the party!",
    "Stay positive.",
    "It's been a while.",
    "Enjoy your vacation!",
    "Let me know your thoughts.",
    "It’s a work in progress.",
    "I’m glad we talked."
];


export const generateRandomName = () => {
    return nameList[Math.floor(Math.random() * nameList.length)];
};

export const generateRandomMessage = () => {
    return messageList[Math.floor(Math.random() * messageList.length)];
};

